
import { useRef } from "react";

export const useOtherRefs = () => {
  return {
    abwSection2Ref: useRef(null),
    liane2Ref: useRef(null),
    liane3Ref: useRef(null),
    liane4Ref: useRef(null),
    watchfaceRef: useRef(null),
    watchleaf2Ref: useRef(null),
    watchleaf3Ref: useRef(null),
    watchleaf4Ref: useRef(null),
    watchleaf5Ref: useRef(null),
    watchleaf6Ref: useRef(null),
    watchleaf7Ref: useRef(null),
    watchleaf8Ref: useRef(null),
    number100prozentRef: useRef(null),
    abwForestPhotoRef: useRef(null),
    zeitRef: useRef(null),
    watchRef: useRef(null),
    watchpointerRef: useRef(null),
    zugebenRef: useRef(null),
    nochsindRef: useRef(null),
    ProzentRef: useRef(null),
    numberlargeRef: useRef(null),
    LandoberflaecheRef: useRef(null),
    abwSection3Ref: useRef(null),
    liane5Ref: useRef(null),
    abwParanussbaumRef: useRef(null),
    abwSection3H2FirstlineRef: useRef(null),
    abwSection3H2SecondlineRef: useRef(null),
    liane2MobileRef: useRef(null),
    liane3MobileRef: useRef(null),
    liane4MobileRef: useRef(null),
    watchfaceMobileRef: useRef(null),
    watchleaf2MobileRef: useRef(null),
    watchleaf3MobileRef: useRef(null),
    watchleaf4MobileRef: useRef(null),
    watchleaf5MobileRef: useRef(null),
    watchleaf6MobileRef: useRef(null),
    watchleaf7MobileRef: useRef(null),
    watchleaf8MobileRef: useRef(null),
    number100prozentMobileRef: useRef(null),
    abwForestPhotoMobileRef: useRef(null),
    zeitMobileRef: useRef(null),
    watchMobileRef: useRef(null),
    watchpointerMobileRef: useRef(null),
    zugebenMobileRef: useRef(null),
    nochsindMobileRef: useRef(null),
    ProzentMobileRef: useRef(null),
    numberlargeMobileRef: useRef(null),
    LandoberflaecheMobileRef: useRef(null),
    abwScrollDownRef:useRef(null),
    abwParanussbaumImageRef:useRef(null),
    abwSection1Ref:useRef(null),
    liane1Ref:useRef(null),
    lianeklein1Ref:useRef(null),
    lianeklein3Ref:useRef(null),
    wiggleLeafRef:useRef(null),
    tree1LeftRef:useRef(null),
    tree2LeftRef : useRef(null),
    tree3LeftRef : useRef(null),
    tree1RightRef : useRef(null),
    tree2RightRef : useRef(null),
    tree3RightRef : useRef(null),
    
    liane1MobileRef : useRef(null),
    lianeklein1MobileRef : useRef(null),
    lianeklein3MobileRef: useRef(null),
    wiggleLeafMobileRef: useRef(null),
    tree1LeftMobileRef: useRef(null),
    tree2LeftMobileRef: useRef(null),
    tree3LeftMobileRef: useRef(null),
    tree1RightMobileRef: useRef(null),
    tree2RightMobileRef: useRef(null),
    tree3RightMobileRef: useRef(null),
  };
};
